### PR TITLE
Allow generating json output via yaml for http action

### PR DESCRIPTION
**Pull request by djmaze**
Example

```yaml
  actions:
    - http:
        target: https://my/url
        headers:
          "Content-Type": "application/json"
        json: true
        body:
          activity: "{{ request.json.pusher.username }} pushed to {{ request.json.repository.name }}"
          title: "{{ request.json.commits | count }} new commits on {{ request.json.ref | replace('refs/heads/', '') }}"
          message: |
              {% for commit in request.json.commits %}
                [{{ commit.id[0:12] }}]({{ commit.url }}): {{ commit.message }}
              {% endfor %}
```

### CODE REVIEW

**Comment by rycus86** [comment]
Nice one, thanks a lot! LGTM, let's just wait until Travis finishes then I'll merge it.

**Comment by djmaze** [comment]
Thanks. I just realized it would be nice to support arrays as well. Well, this could also be implemented later.

**Comment by rycus86** [comment]
True. Up to you then: do you want me to merge it in as is and do the array support later?
The tests in Travis were all green so it can go in if you want.

**Comment by djmaze** [comment]
Would be great to merge now so I can use your docker image already.

**Comment by rycus86** [comment]
Ok, this should be live now. Thanks again!

**Comment by rycus86** [comment]
https://github.com/rycus86/webhook-proxy/commit/d5c260bd984ee22daa97aee97bd7cb7a6853f06d should make this work for arrays too.

**Pull request merged**
