### PR TITLE
Allow templating target url in http action

### PR DESCRIPTION
**Pull request by djmaze**
For example, this allows using `read_config` to read the url from an env variable or docker secret.

### CODE REVIEW

**Comment by rycus86** [comment]
Hey,

Thanks for the PR! Great idea, not sure why it wasn't there in the first place... 🙂

There's a small change: the template render code needs to run when the `_run` function is executing, otherwise it's only set once at initalization. For env vars this works, but not for anything more dynamic.

Could you please implement it the same way `_headers` and `_body` is?

Thanks!

**Comment by djmaze** [comment]
Okay, it is now changed and rebased.

**Comment by rycus86** [comment]
Thanks, merged. The new image should be ready in 20-30 minutes. Thanks again for your PRs! 👍

**Comment by rycus86** [comment]
Sorry, I wasn't checking build emails and Travis had failed... But restarted and should be finished now. Thanks!

**Pull request merged**
