### PR TITLE
Added verify option to http action

### PR DESCRIPTION
**Pull request by zbyrek**
Necessary to allow ignoring certificates (or providing self signed CA) when hosting own servers in local network.

### CODE REVIEW

**Comment by rycus86** [comment]
Thanks for this!

**Comment by rycus86** [comment]
It looks like the Travis integration got broken somewhere in the last ~3 years since the last release. 😅 
Do you need the Docker images built from this repo? If so, let me know, and I'll add a GitHub actions build later.

**Comment by zbyrek** [comment]
It would be nice to get new image with this (for test purposes I just mounted my version of file in docker to overwrite original).
I also want to thank you, this is great project, exactly what I needed.

**Comment by rycus86** [comment]
Thanks! I'll try adding Actions later today.

**Comment by zbyrek** [comment]
If this is big issue, then I could live with current approach.
I don't use docker integration, just standard latest tag.

**Pull request merged**
